[build]
builder = "nixpacks"

[deploy]
startCommand = "bash scripts/prestart.sh && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "PORT"
value = "8000"
